version: '3'

services:
  web:
    build: .
    volumes:
      - /tmp/gunicorn.sock:/tmp/gunicorn.sock
    environment:
      - FLASK_APP=main.py
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /tmp/gunicorn.sock:/tmp/gunicorn.sock
    ports:
      - "8090:8090"
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge