version: '3'

services:
  web:
    build: .
    volumes:
      - gunicorn_socket:/run/gunicorn
    environment:
      - FLASK_APP=main.py
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./custom_nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - gunicorn_socket:/run/gunicorn
    ports:
      - "8090:8090"
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  gunicorn_socket: